### ISSUE TITLE
Current master/MP-1.1 failing to install microservice-vote features

### ISSUE THREAD

**Issue by starksm64** [eclipse/microprofile-conference#177] opened 2017-09-28 23:03 UTC
The current master/MP-1.1 branch are failing to build the microservice-vote module due to the following feature download problem:

[INFO] ------------------------------------------------------------------------
[INFO] Building Conference :: Vote 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ microservice-vote ---
[INFO] Deleting /Users/starksm/Dev/JBoss/Microprofile/upstream-microprofile-conference/microservice-vote/target
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ microservice-vote ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/starksm/Dev/JBoss/Microprofile/upstream-microprofile-conference/microservice-vote/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ microservice-vote ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 32 source files to /Users/starksm/Dev/JBoss/Microprofile/upstream-microprofile-conference/microservice-vote/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ microservice-vote ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/starksm/Dev/JBoss/Microprofile/upstream-microprofile-conference/microservice-vote/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ microservice-vote ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 4 source files to /Users/starksm/Dev/JBoss/Microprofile/upstream-microprofile-conference/microservice-vote/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ microservice-vote ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.microprofile.showcase.vote.api.SessionVoteTest
> allSessionVotes() session1
session2 = [cefa7ca1-d83c-431d-adac-2b88d1d9b7bf]
session1 = [12a48831-56e5-4997-a469-f931edf3958b, 22a88c87-36b2-420c-9339-74271786dfae, 99dde7ec-2d2d-4de2-b21d-4e8ae3f52cc7]
> allSessionVotes() session1
session2 = [a21682f4-ba74-4e74-8848-c9657c293063]
session1 = [2b0c08e4-0987-453d-ab94-7dedb1a0e25d, 7ecda1e5-9d46-4cac-b0d2-b5ea3b205594, f4ad29a7-3e40-4642-8c56-88dc25e1cf51]
> allSessionVotes() session1
session1 = [bc293f04-c2a6-4813-9e12-e08ccaaa0d13]
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.228 sec - in io.microprofile.showcase.vote.api.SessionVoteTest

Results :

Tests run: 10, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- liberty-maven-plugin:1.2.1:install-server (install-liberty) @ microservice-vote ---
[INFO] CWWKM2102I: Using installDirectory : /Users/starksm/Dev/JBoss/Microprofile/upstream-microprofile-conference/microservice-vote/target/wlp.
[INFO] CWWKM2102I: Using serverName : VoteServer.
[INFO] CWWKM2102I: Using serverDirectory : /Users/starksm/Dev/JBoss/Microprofile/upstream-microprofile-conference/microservice-vote/target/wlp/usr/servers/VoteServer.
[INFO] Getting: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/index.yml
[INFO] To: /Users/starksm/.m2/repository/wlp-cache/index.yml
[INFO] Not modified - so not downloaded
[INFO] Getting: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/beta/wlp-beta-2017.9.0.1.zip
[INFO] To: /Users/starksm/.m2/repository/wlp-cache/2017.9.0_1/wlp-beta-2017.9.0.1.zip
[INFO] Not modified - so not downloaded
[INFO] 
[INFO] --- liberty-maven-plugin:1.2.1:install-feature (install-feature) @ microservice-vote ---
[INFO] CWWKM2102I: Using pre-installed assembly : /Users/starksm/Dev/JBoss/Microprofile/upstream-microprofile-conference/microservice-vote/target/wlp.
[INFO] CWWKM2102I: Using serverName : VoteServer.
[INFO] CWWKM2102I: Using serverDirectory : /Users/starksm/Dev/JBoss/Microprofile/upstream-microprofile-conference/microservice-vote/target/wlp/usr/servers/VoteServer.
[INFO] CWWKM2001I: server.config.dir is /Users/starksm/Dev/JBoss/Microprofile/upstream-microprofile-conference/microservice-vote/target/wlp/usr/servers/VoteServer.
[INFO] CWWKM2001I: server.output.dir is /Users/starksm/Dev/JBoss/Microprofile/upstream-microprofile-conference/microservice-vote/target/wlp/usr/servers/VoteServer.
[INFO] CWWKM2001I: Invoke command is [/Users/starksm/Dev/JBoss/Microprofile/upstream-microprofile-conference/microservice-vote/target/wlp/bin/installUtility, install, --acceptLicense, --to=usr, mpConfig-1.0].
[INFO] Establishing a connection to the configured repositories ...
[INFO] This process might take several minutes to complete.
[INFO] 
[INFO] Successfully connected to all configured repositories.
[INFO] 
[INFO] Preparing assets for installation. This process might take several minutes to complete.
[INFO] CWWKF1295E: The mpConfig-1.0 asset cannot be downloaded or installed to IBM WebSphere Application Server Liberty Early Access 2017.9.0.1 because it applies only to the following product editions and versions: 
[INFO] 
[INFO] - IBM WebSphere Application Server Liberty Early Access 2017.9.0.0
[INFO] 
[INFO] Use the installUtility find action to retrieve a list of assets that apply to your installation.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Conference ......................................... SUCCESS [  0.136 s]
[INFO] Conference :: Bootstrap Data ....................... SUCCESS [  2.401 s]
[INFO] Conference :: Session .............................. SUCCESS [  9.768 s]
[INFO] Conference :: Vote ................................. FAILURE [  7.617 s]
[INFO] Conference :: Speaker .............................. SKIPPED
[INFO] Conference :: Schedule ............................. SKIPPED
[INFO] Conference :: Web .................................. SKIPPED
[INFO] Conference :: Start ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20.308 s
[INFO] Finished at: 2017-09-28T16:02:07-07:00
[INFO] Final Memory: 55M/885M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.wasdev.wlp.maven.plugins:liberty-maven-plugin:1.2.1:install-feature (install-feature) on project microservice-vote: CWWKM2002E: Failed to invoke [/Users/starksm/Dev/JBoss/Microprofile/upstream-microprofile-conference/microservice-vote/target/wlp/bin/installUtility, install, --acceptLicense, --to=usr, mpConfig-1.0]. RC= 29 but expected=[0, 22]. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :microservice-vote

**Comment by NottyCode** [comment] 2017-09-29 01:28
Pretty sure this is caused by a problem publishing the most recent Liberty beta. It should be fixed tomorrow.

**Comment by aguibert** [comment] 2017-09-29 13:29
@AndyGee I can work on this, should have a fix shortly.

**Closed** 2017-09-29 14:22 UTC
Labels: bug
